//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMBot.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMBot.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;after&quot;: &quot;76c6c2e28e4833cf2524a4b5730132940a2e05af&quot;,
        ///    &quot;before&quot;: &quot;d979f44796e726573ca0de821c82b9ab54883b98&quot;,
        ///    &quot;commits&quot;: [
        ///        {
        ///            &quot;added&quot;: [],
        ///            &quot;author&quot;: {
        ///                &quot;email&quot;: &quot;james.r.santiago@gmail.com&quot;,
        ///                &quot;name&quot;: &quot;jamessantiago&quot;,
        ///                &quot;username&quot;: &quot;jamessantiago&quot;
        ///            },
        ///            &quot;committer&quot;: {
        ///                &quot;email&quot;: &quot;james.r.santiago@gmail.com&quot;,
        ///                &quot;name&quot;: &quot;jamessantiago&quot;,
        ///                &quot;username&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GithubWebHookJson {
            get {
                return ResourceManager.GetString("GithubWebHookJson", resourceCulture);
            }
        }
    }
}
